version: "3.9"

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: vuln
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/00-schema.sql:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d vuln"]
      interval: 5s
      timeout: 3s
      retries: 20

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql+psycopg://app:app@db:5432/vuln
      API_TOKEN: supersecrettoken    # zmień!
      UVICORN_HOST: 0.0.0.0
      UVICORN_PORT: 8000
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"

  metabase:
    image: metabase/metabase:latest
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
    volumes:
      - mbdata:/metabase-data
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
  mbdata:
