version: "3.9"
services:
  web:
    build: .
    environment:
      APP_TOKEN: changeme-token
      DB_PATH: /data/vuln.sqlite
    ports:
      - "8000:8000"
    volumes:
      - data:/data

volumes:
  data:
