version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vuln-dashboard
    environment:
      APP_TOKEN: changeme-token       # USTAW w prod na losowy długi token
      DB_PATH: /data/vuln.sqlite
      FLASK_ENV: production
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data                  # baza będzie w ./data/vuln.sqlite
    restart: unless-stopped
    command: >
      waitress-serve --host 0.0.0.0 --port 8000 app.app:app
