version: "3.9"

services:
  web:
    container_name: vuln-dashboard
    build: .
    ports:
      - "8000:8000"
    environment:
      APP_TOKEN: ${APP_TOKEN:-changeme-token}
      DB_PATH: /data/vuln.sqlite
    volumes:
      - data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8000/"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  data:
