version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vuln-dashboard
    environment:
      APP_TOKEN: changeme-token
      DB_PATH: /data/vuln.sqlite
      FLASK_ENV: production
    ports:
      - "8000:8000"
    volumes:
      - data:/data              # <— named volume
    restart: unless-stopped
    command: >
      waitress-serve --host 0.0.0.0 --port 8000 app:app

volumes:
  data: {}

