# Clair v4 Configuration File
# Źródło: https://quay.github.io/clair/reference/config.html
# Ten plik zapewnia szerokie pokrycie: Alpine, Debian, Ubuntu, RedHat, GHSA, PYSEC, NVD.

http_listen_addr: ":8080"

indexer:
  connstring: "postgres://clair:clair@localhost:5432/clair?sslmode=disable"
  scanlock_retry: 10
  layer_scan_concurrency: 4
  # Opcjonalnie możesz ustawić: disable_updaters: false

matcher:
  connstring: "postgres://clair:clair@localhost:5432/clair?sslmode=disable"
  indexer_connstring: "postgres://clair:clair@localhost:5432/clair?sslmode=disable"
  max_conn_pool: 100
  # Tryb dopasowania (jeśli Twoja wersja obsługuje)
  mode: aggressive

notifier:
  connstring: "postgres://clair:clair@localhost:5432/clair?sslmode=disable"
  poll_interval: 1m

updaters:
  sets:
    # --- Dystrybucje systemowe ---
    - alpine          # podatności z https://secdb.alpinelinux.org/
    - debian          # podatności z https://security-tracker.debian.org/
    - ubuntu          # podatności z Ubuntu CVE Tracker
    - redhat          # podatności z Red Hat OVAL feed
    - suse            # podatności z SUSE OVAL
    - oracle          # podatności z Oracle Linux
    # --- Ekosystemy aplikacyjne ---
    - ghsa            # GitHub Security Advisories (GHSA)
    - pyupio          # Python Security (PYSEC)
    - nvd             # National Vulnerability Database (NVD)
  filter:
    # Możesz ustawić filtry, np.:
    # exclude:
    #   - "test"
    # include:
    #   - ".*"
  update_interval: 12h  # jak często ma się odświeżać baza
  # proxy: http://proxy:8080  # (opcjonalnie, jeśli CI/CD za NAT-em)

log:
  level: info
  format: text

metrics:
  name: prometheus
  addr: ":6060"

trace:
  name: "jaeger"
  probability: 0.0
